name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      working-directory: ./TestProject
      run: dotnet restore TestProject.sln

    - name: Build
      working-directory: ./TestProject
      run: dotnet build TestProject.sln --configuration Release

    - name: Run tests
      working-directory: ./TestProject
      run: dotnet test TestProject.sln --configuration Release --logger "trx;LogFileName=testresults.trx"

    - name: Coverlet coverage test
      # You may pin to the exact commit or the version.
      # uses: b3b00/coverlet-action@77a2bb02e31fac9d12a64709c94a41266cebec6c
      uses: b3b00/coverlet-action@1.2.5
      with:
        # output filename
        #output: # default is ./lcov.info
        # output format : lcov, json, opencover, cobertura, teamcity (see coverlet documentation)
        #outputFormat: # default is lcov
        # assemblies, namespaces, exclusions (see coverlet documentation)
        #excludes: # optional
        # path to unit test project from repository root
        testProject: ./TestProject/TestProject.Test
        # threshold below which tests fail.
        #threshold: # optional
        # if true, produces extra debugging output. Default is false.
        #debug: # optional

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: testresults.trx
