name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:          
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: TestProject
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --warnaserror

    - name: Run tests
      run: dotnet test --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
    
    - name: Code Coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'TestProject/coverage/*/coverage.cobertura.xml'
        badge: true
        fail_below_min: true
        format: 'markdown'
        output: 'both'
        thresholds: '75 95'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    
  format:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Dotnet format
      run: |
        dotnet tool install -g dotnet-format
        dotnet format --verify-no-changes || echo "[!] You have format errors. Execute "dotnet format" and commit again" && exit 1

    # If you want to automatic push the format changes use the following
    #- name: Dotnet format + Auto-commit changes
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
    #  run: |
    #    dotnet tool install -g dotnet-format
    #    dotnet format
    #    git config user.name "GitHub Actions"
    #    git config user.email "actions@github.com"
    #    branch_name=$GITHUB_HEAD_REF
    #    git diff --exit-code || gh pr checkout ${{ github.event.pull_request.number }} && git commit -am "[Auto-commit] Fix code formatting issues" && git push
  

