name: Dotnet Format

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        working-directory: ./TestProject
        run: |
          dotnet format --verbosity normal
          
      - name: Check for formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT  }}
        run: |
          git config user.name "mpawlow"
          git config user.email "manupaw2000@gmail.com"
          branch_name=$GITHUB_HEAD_REF
          git diff --exit-code || gh pr checkout ${{ github.event.pull_request.number }} && git commit -am "[Auto-commit] Fix code formatting issues" && git push
      
