name: .NET Workflow

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  worflow:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ./TestProject/TestProject.sln
    
    steps:

    - name: Verify source branch
      run: |
        SOURCE_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F'/' '{print $1}')
        if [ "$SOURCE_BRANCH" != "feature" ] && [ "$SOURCE_BRANCH" != "hotfix" ]; then
          echo "Error: Source branch must have 'feature/' or 'hotfix/' prefix."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Echo
      run: echo $SOLUTION_PATH
    
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_PATH

    - name: Build
      working-directory: ./TestProject
      run: | 
        echo $SOLUTION_PATH
        echo "dotnet build $SOLUTION_PATH --configuration Release --warnaserror"
        dotnet build $SOLUTION_PATH --configuration Release --warnaserror

    - name: Run tests
      run: dotnet test $SOLUTION_PATH --configuration Release

    - name: Dotnet format
      run: |
        dotnet tool install -g dotnet-format
        dotnet format --verify-no-changes || echo "Format error. Execute dotnet format and commit again" && exit 1
