name: .NET Workflow

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  worflow:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: TestProject
      SOLUTION_NAME: TestProject.sln
    
    steps:
    - name: Verify source branch
      run: |
        SOURCE_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F'/' '{print $1}')
        if [ "$SOURCE_BRANCH" != "feature" ] && [ "$SOURCE_BRANCH" != "hotfix" ]; then
          echo "Error: Source branch must have 'feature/' or 'hotfix/' prefix."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      working-directory: $WORKING_DIRECTORY
      run: dotnet restore $SOLUTION_NAME

    - name: Build
      working-directory: $WORKING_DIRECTORY
      run: dotnet build $SOLUTION_NAME --configuration Release --warnaserror

    - name: Run tests
      working-directory: $WORKING_DIRECTORY
      run: dotnet test $SOLUTION_NAME --configuration Release

    - name: Dotnet format
      working-directory: $WORKING_DIRECTORY
      run: |
        dotnet tool install -g dotnet-format
        dotnet format --verify-no-changes || echo "[!] You have format errors. Execute "dotnet format" and commit again" && exit 1
