name: Verify source branch

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:          
  source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch
        run: |
          ALLOWED_BRANCHES=("feature" "hotfix" "fix")
          SOURCE_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F'/' '{print $1}')
          if [[ ! " ${ALLOWED_BRANCHES[@]} " =~ " $SOURCE_BRANCH " ]]; then
            echo "Error: Source branch must have one of the allowed prefixes: ${ALLOWED_BRANCHES[*]}"
            exit 1
          fi
