name: Verify PR Source Branch

on:
  pull_request:
    branches:
      - develop

jobs:
  verify-branch:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check source branch prefix
      run: |
        SOURCE_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}" | awk -F'/' '{print $1}')
        if [ "$SOURCE_BRANCH" != "feature" ] && [ "$SOURCE_BRANCH" != "hotfix" ]; then
          echo "Error: Source branch must have 'feature/' or 'hotfix/' prefix."
          exit 1
        fi
